# Generated by Django 5.0.7 on 2024-07-19 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stats_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='username',
            new_name='nickname',
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponentNickname', models.CharField(max_length=200)),
                ('opponentScore', models.IntegerField()),
                ('myScore', models.IntegerField()),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_history', to='base.stats')),
            ],
        ),
    ]
