# Generated by Django 5.0.7 on 2024-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('nb_of_victories', models.IntegerField()),
                ('nb_of_defeats', models.IntegerField()),
                ('badge', models.IntegerField()),
                ('ranking_position', models.IntegerField()),
                ('nb_of_games_played', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
