# Generated by Django 4.2.16 on 2024-09-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='nb_of_games_played',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='ranking_position',
        ),
    ]
