# Generated by Django 4.2.16 on 2024-10-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_remove_stats_badge_remove_stats_nb_of_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='stats',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
