# Generated by Django 4.2.16 on 2024-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_gamehistory_stats_gamehistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='myUsername',
            field=models.CharField(default='default_username', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='opponentUsername',
            field=models.CharField(default='default_username', max_length=200),
        ),
    ]
