# Generated by Django 4.2.16 on 2024-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gamehistory_myusername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='opponentUsername',
            field=models.CharField(max_length=200),
        ),
    ]
