{
 "title": "Pong Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Pong_Database Read By Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_blk_read_time{datname=\"pong_database\"}",
     "legendFormat": "Time spent reading data file blocks by backends in this database, in milliseconds"
    }
   ]
  },
  {
   "title": "Nginx Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "Nginx HTTP Requests Total" }
   ]
  },
  {
   "title": "Django Servers HTTP Responses By Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total",
     "legendFormat": "{{job}}: \"status={{status}}\""
    }
   ]
  }
 ]
}