# Generated by Django 4.2.16 on 2024-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default='default_password', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='default_password', max_length=30),
        ),
    ]
