# Generated by Django 4.2.16 on 2024-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_remove_customuser_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is2fa',
            field=models.BooleanField(default=False),
        ),
    ]
