# Generated by Django 4.2.16 on 2024-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
