# Generated by Django 4.2.16 on 2024-09-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
