# Generated by Django 4.2.16 on 2024-10-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_alter_customuser_is2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, null=True),
        ),
    ]
