# Generated by Django 4.2.16 on 2024-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0009_customuser_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is2fa',
            field=models.BooleanField(default=False),
        ),
    ]
