# Generated by Django 4.2.16 on 2024-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0012_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
