# Generated by Django 4.2.16 on 2024-10-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0012_alter_customuser_is2fa'),
        ('api_user', '0016_alter_customuser_avatar'),
    ]

    operations = [
    ]
