# Generated by Django 4.2.16 on 2024-10-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0015_alter_customuser_is_online'),
        ('api_user', '0017_merge_20241018_1149'),
    ]

    operations = [
    ]
