# Generated by Django 4.2.16 on 2024-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0017_merge_20241018_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
