# Generated by Django 4.2.16 on 2024-10-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0018_customuser_isanonymous'),
        ('api_user', '0018_merge_20241022_1240'),
    ]

    operations = [
    ]
