# Generated by Django 4.2.16 on 2024-10-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0020_customuser_last_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is2fa',
            field=models.BooleanField(default=True),
        ),
    ]
