# Generated by Django 4.2.16 on 2024-10-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0021_alter_customuser_is2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is2fa',
            field=models.BooleanField(default=False),
        ),
    ]
