# Generated by Django 4.2.16 on 2024-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0021_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
