# Generated by Django 4.2.16 on 2024-10-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0022_alter_customuser_is2fa'),
        ('api_user', '0023_alter_customuser_last_login'),
    ]

    operations = [
    ]
